# Generated by Django 4.2.4 on 2023-08-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.room')),
            ],
        ),
    ]
