# Generated by Django 4.2.4 on 2023-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['user_name'], name='user_name'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['email'], name='email'),
        ),
    ]
